### PR TITLE
[Spike] Use GraphQL Ruby's native directives

### PR DESCRIPTION
**Pull request by daemonsy**

### CODE REVIEW

**Comment by jturkel** [comment]
Would using GraphQL Ruby's native directives fix #94?

**Comment by daemonsy** [comment]
@jturkel yes! I was hoping that it would resolve issues that are a result of us having to build a poor version of directives support to print out the directives.

**Comment by bzupnick** [comment]
Is there any update on migrating this Gem over to using the latest `graphql` Gem?

**Comment by jturkel** [comment]
@daemonsy - Is there anything I can do to help with this change? I'd love to get this or #94 landed to fix the inheritance of federation directives.

**Comment by sofie-c** [comment]
Hey @daemonsy - sifting through the PRs here. Can we close this one out?

**Pull request closed without merging**
