### PR TITLE
fix: Make types with a field with a @requires directive entities

### PR DESCRIPTION
**Pull request by FunkyloverOne**
This PR replicates the changes made in https://github.com/Gusto/apollo-federation-ruby/pull/75 on top of a newer codebase.
The changes are quite simple, and I believe are still relevant. 
@daemonsy WDYT?

### CODE REVIEW

**Comment by daemonsy** [comment]
Hey @FunkyloverOne thanks for redoing the PR on top of the changes. I'm taking a look at it .

**Comment by FunkyloverOne** [comment]
Hey @daemonsy, I'm not pushing, just reminding you that those changes are still on top of the latest codebase _for now._ :grinning: 
And they are quite straightforward too, feel free to reach out if I may help you with it.

**Comment by daemonsy** [comment]
Hey @FunkyloverOne apologies on moving so slowly on this. I appreciate the ping.

**Comment by daemonsy** [comment]
@lennyburdette second ping in the same day 😸 . If you're interested in chiming in on this too.

**Comment by lennyburdette** [comment]
@daemonsy is correct—the only way to add a type to the `_Entity` union is by defining a `@key` directive. If the example described in #75 worked, that would be a bug and is most likely fixed in Federation 2 (which has much more complete validation logic.)

**Comment by FunkyloverOne** [comment]
Hey guys, thank you for your feedback! Now I realize it doesn't make sense, sorry for bothering you with this, closing this PR now.

**Pull request closed without merging**
