### PR TITLE
chore(deps): Allow for GraphQL dependencies >= 1.10.0

### PR DESCRIPTION
**Pull request by HectorMF**
graphql-ruby 1.10.0 brought some breaking changes to its to_graphql method. See: https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1100-20-jan-2020

### CODE REVIEW

**Comment by grxy** [comment]
@HectorMF Overall, this looks good. Mind addressing the merge conflicts and lint issues?

**Comment by HectorMF** [comment]
@grxy Sorry forgot to finish this.  I've had to pull out some of the code from the to_graphql function to pass the complexity cops.  Let me know if there is anything you want me to change

**Comment by tjwallace** [comment]
Anything left to do here? Would be great to be able to update `graphql` to the latest version when using `apollo-federation`. Thanks!

**Comment by Amandeepsinghghai** [comment]
First of all thanks for the work @HectorMF @grxy . Really appreciate it.

It would be great if this could be merged in so that we can start pointing to the main repo instead of a fork. 

Am I missing something or there is still some work left on the PR?

**Comment by Amandeepsinghghai** [comment]
First of all thanks for the work @HectorMF @grxy . Really appreciate it.

It would be great if this could be merged in so that we can start pointing to the main repo instead of a fork. 

Am I missing something or there is still some work left on the PR?

**Comment by BatuhanW** [comment]
Guys, thanks for this 🙏 When will this be released?

**Comment by tjwallace** [comment]
Can others confirm this works with `graphql-ruby` 1.10.x? I'm having this problem #63

**Comment by bilby91** [comment]
I've found that the gem works with 1.10 as long as you don't use the new interpreter. There are multiple things that need to be fixed. I'm following on #63

**Pull request merged**
